from __future__ import annotations

from copy import deepcopy


FINGER_JOINTS = (
    "thumb_cmc_opposition",
    "thumb_cmc_abduction",
    "thumb_mcp_flexion",
    "thumb_ip_flexion",
    "index_mcp_abduction",
    "index_mcp_flexion",
    "index_pip_flexion",
    "index_dip_flexion",
    "middle_mcp_abduction",
    "middle_mcp_flexion",
    "middle_pip_flexion",
    "middle_dip_flexion",
    "ring_mcp_abduction",
    "ring_mcp_flexion",
    "ring_pip_flexion",
    "ring_dip_flexion",
    "little_mcp_abduction",
    "little_mcp_flexion",
    "little_pip_flexion",
    "little_dip_flexion",
)

FINGER_GROUP_MAP = {
    "thumb": ("thumb_cmc_opposition", "thumb_cmc_abduction", "thumb_mcp_flexion", "thumb_ip_flexion"),
    "index": ("index_mcp_abduction", "index_mcp_flexion", "index_pip_flexion", "index_dip_flexion"),
    "middle": ("middle_mcp_abduction", "middle_mcp_flexion", "middle_pip_flexion", "middle_dip_flexion"),
    "ring": ("ring_mcp_abduction", "ring_mcp_flexion", "ring_pip_flexion", "ring_dip_flexion"),
    "little": ("little_mcp_abduction", "little_mcp_flexion", "little_pip_flexion", "little_dip_flexion"),
}

NORMALIZED_FINGER_LENGTHS = {
    "thumb": 0.70,
    "index": 0.90,
    "middle": 1.00,
    "ring": 0.93,
    "little": 0.75,
}

OPEN_HAND = {
    "thumb_cmc_opposition": 0.18,
    "thumb_cmc_abduction": 0.22,
    "thumb_mcp_flexion": 0.08,
    "thumb_ip_flexion": 0.04,
    "index_mcp_abduction": -0.08,
    "index_mcp_flexion": 0.04,
    "index_pip_flexion": 0.03,
    "index_dip_flexion": 0.02,
    "middle_mcp_abduction": 0.00,
    "middle_mcp_flexion": 0.04,
    "middle_pip_flexion": 0.03,
    "middle_dip_flexion": 0.02,
    "ring_mcp_abduction": 0.05,
    "ring_mcp_flexion": 0.04,
    "ring_pip_flexion": 0.03,
    "ring_dip_flexion": 0.02,
    "little_mcp_abduction": 0.11,
    "little_mcp_flexion": 0.04,
    "little_pip_flexion": 0.03,
    "little_dip_flexion": 0.02,
}


def _with_open(**updates: float) -> dict[str, float]:
    targets = dict(OPEN_HAND)
    targets.update(updates)
    return targets


GRASP_PRIMITIVES: dict[str, dict] = {
    "SHOW_HAND": {
        "grasp_name": "SHOW_HAND",
        "required_object_type": "none",
        "finger_roles": {
            "thumb": "opposition_display",
            "index": "open_display",
            "middle": "open_display",
            "ring": "open_display",
            "little": "open_display",
        },
        "preshape_joint_targets": OPEN_HAND,
        "contact_target_regions": {},
        "closure_sequence": ["thumb_abduction", "index_middle_curl", "ring_little_curl", "open"],
        "contact_verification": ["five_fingers_visible", "thumb_opposition_visible"],
        "stability_score": "not_applicable",
        "lift_or_manipulation_strategy": "display skeletal hand and independent joints",
        "release_strategy": "return to open hand",
        "failure_recovery": "not_applicable",
    },
    "SPHERICAL_ENCLOSURE_GRASP": {
        "grasp_name": "SPHERICAL_ENCLOSURE_GRASP",
        "required_object_type": "sphere",
        "finger_roles": {
            "thumb": "primary_opposition",
            "index": "upper_support",
            "middle": "opposing_support",
            "ring": "lower_support",
            "little": "stabilizer",
        },
        "preshape_joint_targets": _with_open(
            thumb_cmc_opposition=1.06,
            thumb_cmc_abduction=0.48,
            thumb_mcp_flexion=0.76,
            thumb_ip_flexion=0.48,
            index_mcp_abduction=-0.16,
            index_mcp_flexion=0.88,
            index_pip_flexion=0.86,
            index_dip_flexion=0.52,
            middle_mcp_abduction=-0.03,
            middle_mcp_flexion=0.98,
            middle_pip_flexion=0.90,
            middle_dip_flexion=0.54,
            ring_mcp_abduction=0.07,
            ring_mcp_flexion=1.04,
            ring_pip_flexion=0.96,
            ring_dip_flexion=0.60,
            little_mcp_abduction=0.13,
            little_mcp_flexion=1.00,
            little_pip_flexion=0.92,
            little_dip_flexion=0.58,
        ),
        "contact_target_regions": {
            "thumb": "lateral sphere surface",
            "index": "upper/front opposite surface",
            "middle": "main opposite surface",
            "ring": "lower/back support",
            "little": "lower stabilizing support",
        },
        "closure_sequence": ["index", "middle", "ring", "little", "thumb"],
        "contact_verification": ["thumb_contact", "active_finger_count >= 4", "sphere_center_inside_finger_cage"],
        "stability_score": "cage_stability_score",
        "lift_or_manipulation_strategy": "hold with all five fingers after verification",
        "release_strategy": "open thumb and supports gradually",
        "failure_recovery": "increase thumb opposition and lower finger support",
    },
    "OPPOSING_FACE_CUBE_GRASP": {
        "grasp_name": "OPPOSING_FACE_CUBE_GRASP",
        "required_object_type": "cube",
        "finger_roles": {
            "thumb": "primary_opposition",
            "index": "opposing_support",
            "middle": "opposing_support",
            "ring": "lower_support",
            "little": "curled_clearance",
        },
        "preshape_joint_targets": _with_open(
            thumb_cmc_opposition=0.92,
            thumb_cmc_abduction=0.40,
            thumb_mcp_flexion=0.62,
            thumb_ip_flexion=0.38,
            index_mcp_abduction=-0.14,
            index_mcp_flexion=0.74,
            index_pip_flexion=0.66,
            index_dip_flexion=0.34,
            middle_mcp_abduction=-0.02,
            middle_mcp_flexion=0.78,
            middle_pip_flexion=0.68,
            middle_dip_flexion=0.36,
            ring_mcp_abduction=0.12,
            ring_mcp_flexion=0.70,
            ring_pip_flexion=0.58,
            ring_dip_flexion=0.30,
            little_mcp_abduction=0.22,
            little_mcp_flexion=0.56,
            little_pip_flexion=0.48,
            little_dip_flexion=0.26,
        ),
        "contact_target_regions": {
            "thumb": "center of one cube face",
            "index": "center of opposing face",
            "middle": "opposing face support",
            "ring": "lower edge support",
            "little": "clearance curl",
        },
        "closure_sequence": ["index", "thumb", "middle", "ring"],
        "contact_verification": ["opposing_face_contact", "one_face_only_contact == false", "corner_contact_penalty low"],
        "stability_score": "cube_contact_symmetry_score",
        "lift_or_manipulation_strategy": "hold between opposing faces only after verification",
        "release_strategy": "open thumb/index first, then lower supports",
        "failure_recovery": "recenter on opposing face pair",
    },
    "LATERAL_CYLINDER_BODY_GRASP": {
        "grasp_name": "LATERAL_CYLINDER_BODY_GRASP",
        "required_object_type": "cylinder_horizontal_or_vertical",
        "finger_roles": {
            "thumb": "primary_opposition",
            "index": "opposing_support",
            "middle": "opposing_support",
            "ring": "lower_support",
            "little": "stabilizer",
        },
        "preshape_joint_targets": _with_open(
            thumb_cmc_opposition=1.04,
            thumb_cmc_abduction=0.46,
            thumb_mcp_flexion=0.70,
            thumb_ip_flexion=0.44,
            index_mcp_abduction=-0.15,
            index_mcp_flexion=0.92,
            index_pip_flexion=0.84,
            index_dip_flexion=0.50,
            middle_mcp_abduction=-0.02,
            middle_mcp_flexion=0.96,
            middle_pip_flexion=0.88,
            middle_dip_flexion=0.52,
            ring_mcp_abduction=0.07,
            ring_mcp_flexion=0.96,
            ring_pip_flexion=0.88,
            ring_dip_flexion=0.52,
            little_mcp_abduction=0.13,
            little_mcp_flexion=0.88,
            little_pip_flexion=0.80,
            little_dip_flexion=0.46,
        ),
        "contact_target_regions": {
            "thumb": "one side of cylinder body",
            "index": "opposite side near centerline",
            "middle": "opposite side support",
            "ring": "lower body support",
            "little": "under-body stabilizer",
        },
        "closure_sequence": ["index", "middle", "thumb", "ring", "little"],
        "contact_verification": ["side_body_contact_verified", "top_down_cylinder_grasp_used == false"],
        "stability_score": "multi_side_contact_score",
        "lift_or_manipulation_strategy": "rotate only after lateral body contact verification",
        "release_strategy": "open thumb/index while preserving support",
        "failure_recovery": "retry lateral midpoint grasp",
    },
    "CAPSULE_CENTER_SUPPORT_GRASP": {
        "grasp_name": "CAPSULE_CENTER_SUPPORT_GRASP",
        "required_object_type": "capsule",
        "finger_roles": {
            "thumb": "primary_opposition",
            "index": "opposing_support",
            "middle": "opposing_support",
            "ring": "lower_support",
            "little": "stabilizer",
        },
        "preshape_joint_targets": _with_open(
            thumb_cmc_opposition=0.82,
            thumb_cmc_abduction=0.34,
            thumb_mcp_flexion=0.58,
            thumb_ip_flexion=0.34,
            index_mcp_flexion=0.76,
            index_pip_flexion=0.70,
            middle_mcp_flexion=0.80,
            middle_pip_flexion=0.74,
            ring_mcp_flexion=0.82,
            ring_pip_flexion=0.76,
            little_mcp_flexion=0.74,
            little_pip_flexion=0.68,
        ),
        "contact_target_regions": {"all": "center of mass support, avoid rounded ends"},
        "closure_sequence": ["index", "middle", "thumb", "ring", "little"],
        "contact_verification": ["center_support", "no_end_only_contact"],
        "stability_score": "capsule_center_support_score",
        "lift_or_manipulation_strategy": "hold near center of mass",
        "release_strategy": "controlled release",
        "failure_recovery": "recenter object in grasp envelope",
    },
    "TRIPOD_PRECISION_GRASP": {
        "grasp_name": "TRIPOD_PRECISION_GRASP",
        "required_object_type": "stylus",
        "finger_roles": {
            "thumb": "primary_opposition",
            "index": "fingertip_precision",
            "middle": "lower_support",
            "ring": "curled_clearance",
            "little": "curled_clearance",
        },
        "preshape_joint_targets": _with_open(
            thumb_cmc_opposition=0.72,
            thumb_cmc_abduction=0.30,
            thumb_mcp_flexion=0.46,
            thumb_ip_flexion=0.24,
            index_mcp_abduction=-0.02,
            index_mcp_flexion=0.34,
            index_pip_flexion=0.26,
            index_dip_flexion=0.12,
            middle_mcp_abduction=0.02,
            middle_mcp_flexion=0.50,
            middle_pip_flexion=0.42,
            middle_dip_flexion=0.20,
            ring_mcp_abduction=0.05,
            ring_mcp_flexion=0.74,
            ring_pip_flexion=0.68,
            ring_dip_flexion=0.36,
            little_mcp_abduction=0.12,
            little_mcp_flexion=0.74,
            little_pip_flexion=0.68,
            little_dip_flexion=0.36,
        ),
        "contact_target_regions": {
            "thumb": "stylus handle side",
            "index": "upper/front control side",
            "middle": "lower/opposite support side",
        },
        "closure_sequence": ["thumb", "middle", "index"],
        "contact_verification": ["thumb_contact", "index_contact", "middle_contact", "ring_little_clearance_ok"],
        "stability_score": "tripod_precision_score",
        "lift_or_manipulation_strategy": "carry stylus tip to checkpoint",
        "release_strategy": "open index then thumb/middle",
        "failure_recovery": "regrasp at handle center",
    },
    "INDEX_FINGERTIP_PRESS": {
        "grasp_name": "INDEX_FINGERTIP_PRESS",
        "required_object_type": "button",
        "finger_roles": {
            "thumb": "curled_clearance",
            "index": "fingertip_precision",
            "middle": "curled_clearance",
            "ring": "curled_clearance",
            "little": "curled_clearance",
        },
        "preshape_joint_targets": _with_open(
            thumb_cmc_opposition=0.38,
            thumb_cmc_abduction=0.22,
            thumb_mcp_flexion=0.24,
            thumb_ip_flexion=0.12,
            index_mcp_abduction=-0.02,
            index_mcp_flexion=0.22,
            index_pip_flexion=0.16,
            index_dip_flexion=0.08,
            middle_mcp_flexion=0.68,
            middle_pip_flexion=0.62,
            middle_dip_flexion=0.34,
            ring_mcp_flexion=0.70,
            ring_pip_flexion=0.64,
            ring_dip_flexion=0.36,
            little_mcp_flexion=0.68,
            little_pip_flexion=0.62,
            little_dip_flexion=0.34,
        ),
        "contact_target_regions": {"index": "button center"},
        "closure_sequence": ["index_extend_press"],
        "contact_verification": ["index_fingertip_contact_button", "non_index_button_contacts == 0"],
        "stability_score": "button_displacement",
        "lift_or_manipulation_strategy": "press along button normal",
        "release_strategy": "retract index",
        "failure_recovery": "recenter index fingertip over button",
    },
    "IN_HAND_ROTATION": {
        "grasp_name": "IN_HAND_ROTATION",
        "required_object_type": "cylinder",
        "finger_roles": {
            "thumb": "counterhold",
            "index": "tangential_push",
            "middle": "opposing_support",
            "ring": "lower_support",
            "little": "stabilizer",
        },
        "preshape_joint_targets": _with_open(
            thumb_cmc_opposition=0.96,
            thumb_cmc_abduction=0.34,
            thumb_mcp_flexion=0.68,
            thumb_ip_flexion=0.42,
            index_mcp_abduction=-0.08,
            index_mcp_flexion=0.60,
            index_pip_flexion=0.36,
            index_dip_flexion=0.18,
            middle_mcp_flexion=0.92,
            middle_pip_flexion=0.84,
            middle_dip_flexion=0.48,
            ring_mcp_flexion=0.94,
            ring_pip_flexion=0.86,
            ring_dip_flexion=0.50,
            little_mcp_flexion=0.82,
            little_pip_flexion=0.74,
            little_dip_flexion=0.42,
        ),
        "contact_target_regions": {
            "index": "tangent push on cylinder body",
            "thumb": "counterhold side",
            "middle_ring": "support arc",
        },
        "closure_sequence": ["support_lock", "index_push", "finger_gait_reposition"],
        "contact_verification": ["min_active_fingers_during_rotation >= 3", "rotation_error below threshold"],
        "stability_score": "stable_hold_during_rotation",
        "lift_or_manipulation_strategy": "gradual hybrid contact-aware cylinder rotation",
        "release_strategy": "return to lateral support before release",
        "failure_recovery": "slow rotation and increase support",
    },
    "CAP_KNOB_ROTATION_224": {
        "grasp_name": "CAP_KNOB_ROTATION_224",
        "required_object_type": "cap_knob",
        "finger_roles": {
            "thumb": "counterhold",
            "index": "tangential_push",
            "middle": "opposing_support",
            "ring": "lower_support",
            "little": "stabilizer",
        },
        "preshape_joint_targets": _with_open(
            thumb_cmc_opposition=1.02,
            thumb_cmc_abduction=0.48,
            thumb_mcp_flexion=0.72,
            thumb_ip_flexion=0.46,
            index_mcp_abduction=-0.14,
            index_mcp_flexion=0.74,
            index_pip_flexion=0.46,
            index_dip_flexion=0.22,
            middle_mcp_abduction=-0.02,
            middle_mcp_flexion=0.92,
            middle_pip_flexion=0.82,
            middle_dip_flexion=0.46,
            ring_mcp_abduction=0.08,
            ring_mcp_flexion=0.96,
            ring_pip_flexion=0.84,
            ring_dip_flexion=0.48,
            little_mcp_abduction=0.14,
            little_mcp_flexion=0.88,
            little_pip_flexion=0.76,
            little_dip_flexion=0.42,
        ),
        "contact_target_regions": {
            "thumb": "cap side counterhold",
            "index": "visible tangential marker push region",
            "middle": "opposing cap side support",
            "ring": "lower stabilizing side",
            "little": "optional lower stabilizer",
        },
        "closure_sequence": ["thumb_middle_counterhold", "ring_little_stabilize", "index_tangential_push"],
        "contact_verification": ["active_finger_count >= 4", "cap_contact_balance_score high", "no_snap_verified"],
        "stability_score": "cap_contact_balance_score",
        "lift_or_manipulation_strategy": "minimum-jerk tactile-inspired 224 degree cap twist after verified contact",
        "release_strategy": "hold final angle, then gradually open",
        "failure_recovery": "pause, increase pressure target, restore counterhold, resume slower twist",
    },
    "SLIP_RECOVERY_REGRASP": {
        "grasp_name": "SLIP_RECOVERY_REGRASP",
        "required_object_type": "any",
        "finger_roles": {
            "thumb": "primary_opposition",
            "index": "opposing_support",
            "middle": "opposing_support",
            "ring": "lower_support",
            "little": "stabilizer",
        },
        "preshape_joint_targets": _with_open(
            thumb_cmc_opposition=0.98,
            thumb_mcp_flexion=0.72,
            index_mcp_flexion=0.88,
            middle_mcp_flexion=0.90,
            ring_mcp_flexion=0.94,
            little_mcp_flexion=0.90,
        ),
        "contact_target_regions": {"all": "restore multi-finger support around current object center"},
        "closure_sequence": ["pause", "tighten_thumb", "add_ring_little_support", "verify"],
        "contact_verification": ["active_finger_count >= 3", "slip_distance below threshold"],
        "stability_score": "post_recovery_stability_score",
        "lift_or_manipulation_strategy": "resume previous task after recovery",
        "release_strategy": "controlled release if recovery fails",
        "failure_recovery": "mark object failed and continue",
    },
    "CONTROLLED_RELEASE": {
        "grasp_name": "CONTROLLED_RELEASE",
        "required_object_type": "any",
        "finger_roles": {
            "thumb": "release",
            "index": "release",
            "middle": "release",
            "ring": "release",
            "little": "release",
        },
        "preshape_joint_targets": OPEN_HAND,
        "contact_target_regions": {},
        "closure_sequence": ["open_thumb_index", "open_supports", "retract_hand"],
        "contact_verification": ["object_remains_at_release_pose"],
        "stability_score": "release_success",
        "lift_or_manipulation_strategy": "not_applicable",
        "release_strategy": "open gradually and retract",
        "failure_recovery": "reopen and hold final state",
    },
}

GRASP_ALIASES = {
    "SPHERICAL_POWER_GRASP": "SPHERICAL_ENCLOSURE_GRASP",
    "CUBIC_FACE_GRASP": "OPPOSING_FACE_CUBE_GRASP",
    "CYLINDER_SIDE_BODY_GRASP": "LATERAL_CYLINDER_BODY_GRASP",
    "CYLINDRICAL_POWER_GRASP": "LATERAL_CYLINDER_BODY_GRASP",
    "TRIPOD_TOOL_GRASP": "TRIPOD_PRECISION_GRASP",
    "BUTTON_PRESS": "INDEX_FINGERTIP_PRESS",
    "IN_HAND_ROTATION_GRASP": "IN_HAND_ROTATION",
    "CAP_KNOB_ROTATION": "CAP_KNOB_ROTATION_224",
    "CAP_ROTATION_GRASP": "CAP_KNOB_ROTATION_224",
}


def canonical_grasp_name(grasp_name: str) -> str:
    key = grasp_name.upper()
    return GRASP_ALIASES.get(key, key)


def get_grasp_preset(grasp_name: str) -> dict:
    key = canonical_grasp_name(grasp_name)
    if key not in GRASP_PRIMITIVES:
        raise KeyError(f"Unknown grasp primitive: {grasp_name}")
    return deepcopy(GRASP_PRIMITIVES[key])


def list_grasp_names() -> list[str]:
    return sorted(GRASP_PRIMITIVES)
